### ISSUE TITLE
resolve issue reported by RustSec

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-spdm#140]

**Comment by haowqs** [comment]
Some advisories and licenses failed

![image](https://user-images.githubusercontent.com/39472702/132985003-fb00e913-027c-4ac5-bbc9-50c398b982f4.png)
![image](https://user-images.githubusercontent.com/39472702/132985031-d503a6f3-e04c-40ca-9706-ad55a1ae34da.png)
![image](https://user-images.githubusercontent.com/39472702/132985041-3f1abd0d-d1fd-4a4a-8ce2-6a302b5b328e.png)

**Comment by jyao1** [comment]
we are using cargo deny now.
