### ISSUE TITLE
fix build fail when using rust-toolchain 2021-08-20

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-spdm#147]
It may be related to https://doc.rust-lang.org/beta/unstable-book/library-features/global-asm.html?highlight=global#global_asm

try options(att_syntax)

**Comment by jyao1** [comment]
other ref: https://doc.rust-lang.org/beta/unstable-book/library-features/asm.html

https://blog.rust-lang.org/inside-rust/2020/06/08/new-inline-asm.html

https://doc.rust-lang.org/beta/unstable-book/library-features/llvm-asm.html

**Comment by haowqs** [comment]
#[cfg(not(feature = "use_tdx_emulation"))]
global_asm!(include_str!("Tdvmcall.s"), options(att_syntax));

Option (att_syntax) fixed assembly error
