### ISSUE TITLE
Decouple SpdmDeviceIo from contexts ?

### ISSUE THREAD

**Issue by andrewjstone** [jyao1/rust-spdm#170]
Hi maintainers,

Thank you for the wonderful project! 

I'm opening this issue only to see if you are open to me making the change described below. Such a change will be relatively invasive, but will not change the core logic of the protocol, which should hopefully make it straightforward to review. 

I'm looking to abstract out the `SpdmDeviceIo` from inside the `SpdmContext` and correspondingly the `RequesterContext` and `ResponderContext`. The end result is that the `send_receive_xxx` calls such as `send_receive_spdm_key_exchange` will be split into multiple methods. First a message is created and returned. Then the caller uses some mechanism(possibly an existing`io_device`), to send the message. Then the caller uses the same mechanism to receive and return a message. Finally a method is called to handle the received message. In a synchronous world this would look something like:

```rust
let send_used = request_ctx.spdm_key_exchange_req(send_buf, slot_id, measurement_summary_hash_type);
io_device.send_message(&send_buf[..send_used])?;
let received_used = io_device.receive_message(&mut recv_buf)?;
request_ctx.spdm_handle_key_exchange_rsp(&recv_buf[..receive_used])?;
```

If such a change was made, we could still keep the `RequesterCtx::send_receive_xxx` methods, but the internals would look similar to above. The signature would just change to take a `&mut dyn SpdmDeviceIO` rather than embedding it in the context. This would allow the calling code, such as `RequesterCtx::start_session` to continue to use this synchronous send/receive pattern. It would also allow other users to reuse the message creation and handler code without having to use a `SpdmDeviceIo`. This opens up the code base to being used in different contexts than originally anticipated, and will also likely make it easier to test.

It could even make sense to break the raw message creation and handler methods into their own types that can be used by the `RequesterContext` and `ResponderContext`. That would allow maintaining the same external interfaces to the contexts, including making the SpdmDeviceIo a member of `RequesterContext` and `ResponderContext`, just not `SpdmContext`. Such a change would allow different use cases from yours to use the bulk of the code from the lower level types, while the higher level types could still be used ergonomically for your purposes.

Now that I've described the change, let me describe my use cases which I'm using to justify such a change.

I have two vastly different use cases for SPDM:
 1. An embedded kernel running on a micro-controller with limited resources
 2. A secure bootstrapping mechanism in user space that will require many simultaneous network connections.

For the first case, tasks in our OS cannot share text, so removing the blocking `SpdmDeviceIO` calls from the protocol logic allows us to write code such that multiple sessions can live in a single kernel task without having to duplicate all the compiled code for this library.

For the second case, we are trying to use spdm for remote attestation purposes over TCP for 10s to potentially 100s of endpoints. We'd prefer not to have to maintain a thread per connection, and instead use async io. 

The recommended change above would enable both of those and expand the reach of this code base to new domains. I hope you are ok with it!

Thank you for your time and consideration.

**Comment by jyao1** [comment]
Thanks for the suggestion. I think it is reasonable. 
I assign it to you. Feel free to submit PR.

**Comment by andrewjstone** [comment]
Great. Thank you.

**Comment by andrewjstone** [comment]
Hi @jyao1, 

I started working on this and implemented the change for `RequesterContext::send_receive_spdm_version`. I came up with a couple of questions that I put in the [commit](https://github.com/oxidecomputer/rust-spdm/commit/8c5c9ee4cf779b41efd48b393dc92184d78b3e50) message and that I'd like your input on. The commit itself is pretty small.

When you get a chance, can you please take a look and tell me your opinions about my questions?
