### ISSUE TITLE
Question: OpaqueErrorData implementation vs SPDM spec (1.1.1 and 1.2WIP)

### ISSUE THREAD

**Issue by andrewjstone** [jyao1/rust-spdm#219]
Hi @jyao1 and team,

I noticed when looking at the SPDM 1.2WIP spec (and then going back to 1.1.1) that in table 51 (of 1.2 spec) `ExtendedErrorData`, there is a vendor/standards defined `OpaqueErrorData` field of variable size. However, there is no way to determine the size of that field from the message itself, unlike all other variable sized fields that I have seen in the spec. When I realized this I got confused and took a look at your [implementation](https://github.com/jyao1/rust-spdm/blame/master/spdmlib/src/message/error.rs#L80-L83).

I noticed that you define `ExtendedErrorData` for vendor specific messages from table 51 differently from the spec, in that you treat the first byte as the length of the remaining data, whereas the spec defines the first byte as the length of the `VendorId`, with the size of the remaining data undefined, except for being capped at a max of 32 bytes including the prior 2 fields. 

I have a few questions with regards to this and was hoping you could help.

1. Is this just a bug in your code, an example from a prior spec, or do you anticipate the spec changing?
2. Does it seem wrong that the spec does not define a length for this field, or is it implied that we will use the size of the message as framed by the transport? This usage of transport size differs from the rest of the messages and is not written out explicitly which is the cause of my concern.

Thank you for your help.

**Comment by jyao1** [comment]
I am following Table 47 — ERROR response message format in SPDM 1.2 spec. The MAX ExtendedErrorData is 32 bytes.

The data_size is only needed in SpdmErrorResponseVendorExtData for internal tracking purpose.
But data_size will NOT be sent or received - you may check the encode() or read() function.

**Comment by andrewjstone** [comment]
Thanks for the quick response @jyao1. I see that the max response is 32 bytes. But how does the implementation know how many of those 32 bytes are actually in a message on the wire when it only knows that the message is an external vendor defined message and therefore has between 1 and 32 bytes. Is it relying on the size of the buffer passed in by transport framing? In short, how can we just read this data and return it to a caller if we don't know its size?

**Comment by jyao1** [comment]
No such info. The code just *tries* to read and break if fail.

```
        for d in &mut data {
            let result = u8::read(r);
            match result {
                Some(v) => {
                    *d = v;
                    data_size += 1;
                }
                None => {
                    break;
                }
            }
```

**Comment by andrewjstone** [comment]
> Right. it is relying on the size of the buffer passed in by transport framing. The code just _tries_ to read and break if fail.
That makes perfect sense here, it just seemed odd compared to the rest of the messages that seemed to always have size info. I appreciate the clarity.

My knowledge of embedded transports is not great, but do all of them have framing? In other words, this will always work because there is a hard size boundary. If not this could be problematic. At a minimum though, maybe the spec should add some wording around it.

**Comment by jyao1** [comment]
Ideally, it should be clear on vendor defined data format.

If you have feedback to SPDM spec, then please submit to DMTF.

**Comment by andrewjstone** [comment]
> If you have feedback to SPDM spec, then please submit to DMTF.

I'm working on figuring that part out. Probably more likely after the new year. Thanks again for all your help!
