### ISSUE TITLE
Build error  `const extern fn` definitions are unstable.

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#260]
Build failed.

error[E0658]: `const extern fn` definitions are unstable
Error:     --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.127/src/macros.rs:188:17
     |
188  | /                 pub $($constness)* unsafe extern fn $i($($arg: $argty),*
189  | |                 ) -> $ret {
190  | |                     $($body);*
191  | |                 }
     | |_________________^
     |
    ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.127/src/unix/linux_like/mod.rs:1490:1
     |
1490 | / f! {
1491 | |     pub fn CMSG_FIRSTHDR(mhdr: *const msghdr) -> *mut cmsghdr {
1492 | |         if (*mhdr).msg_controllen as usize >= ::mem::size_of::<cmsghdr>() {
1493 | |             (*mhdr).msg_control as *mut cmsghdr
...    |
1536 | |     }
1537 | | }
     | |_- in this macro invocation
     |
     = note: see issue #64926 <https://github.com/rust-lang/rust/issues/64926> for more information
     = help: add `#![feature(const_extern_fn)]` to the crate attributes to enable
     = note: this error originates in the macro `f` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: `const extern fn` definitions are unstable

**Comment by davidli2010** [comment]
`const_extern_fn` is stabilized in Rust 1.62, so you should upgrade your local rust toolchain to 1.62 by `rustup update`.

**Comment by xiaoyuxlu** [comment]
Fixed https://github.com/jyao1/rust-spdm/pull/261
