### ISSUE TITLE
crypto function may fail in multiple threads environment.

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#307]
`OnceCell` `try_get_or_init` may return `WouldBlock` in multiple threads environment.
It may cause crypto functions(eg, crypto::aead::encrypt) fail.

**Comment by jyao1** [comment]
we are in single thread env

**Comment by longlongyang** [comment]
Option1: ref https://stackoverflow.com/a/58006287
basic idea: Add an initialization function to the beginning of every test function

Option2: ref https://stackoverflow.com/a/63442117
basic idea: Use a crate to force a setup function be called before all other tests.

**Comment by xiaoyuxlu** [comment]
rust-spdm requires register the crypto function before use. 
For test, RUST_TEST_THREADS=1 can be set to avoid the issue.
When rust test framework support global initialization, I think it will be the right time to remove RUST_TEST_THREAD=1.

**Comment by jyao1** [comment]
OK. let's defer it.
