### ISSUE TITLE
[Question] why need to configure 3 version of SPDM?

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#316]
https://github.com/jyao1/rust-spdm/blob/b85b584a748236809a9ad57bc921316055d39fad/spdmlib/src/common/mod.rs#L415

Is SDPM protocol backward compatible? 
If yes, I think it should be improved.

**Comment by jyao1** [comment]
Current SPDM 1.0, 1.1, 1.2 is included in message header.
