### ISSUE TITLE
Cargo clippy warning  the `Err`-variant returned from this function is very large

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#340]
warning: the `Err`-variant returned from this function is very large
  --> spdmlib/src/responder/context.rs:65:10
   |
65 |     ) -> Result<bool, (usize, [u8; config::DATA_TRANSFER_SIZE])> {
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 4872 bytes
   |
   = help: try reducing the size of `(usize, [u8; _])`, for example by boxing large elements or replacing it with `Box<(usize, [u8; _])>`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
   = note: `#[warn(clippy::result_large_err)]` on by default

**Comment by jyao1** [comment]
See https://github.com/intel/rust-spdm/issues/35
