### ISSUE TITLE
mutable refs (SpdmDeviceIo/SpdmTransportEncap) in SpdmContext

### ISSUE THREAD

**Issue by mxu9** [jyao1/rust-spdm#380]
Currently there are 2 &mut dyn traits (SpdmDeviceIo/SpdmTransportEncap) stored in SpdmContext. This makes hard to design a SpdmServer which can manage multiple spdm connections (responder-requester).

Because it needs a stream (TcpStream) as input parameter to create a SocketIoTransport object. After the object is passed to SpdmContext as mutable traits, the stream cannot be used outside. But in a typical Server (such as TlsServer), the stream is needed (such as register epoll events).

One of the solution is to remove these 2 mutable refs from SpdmContext. Instead they can be provided as input parameters in SpdmContext functions, such as send_message (&[u8], &mut dyn transport_encap, &mut dyn device_io).

**Comment by jyao1** [comment]
Check with @mxu9. We dont need this any more.
