### ISSUE TITLE
lack information of VendorDefinedPayload

### ISSUE THREAD

**Issue by mxu9** [jyao1/rust-spdm#382]
vendor_defined_request_handler is called when responder receives a VendorDefinedPayload. The input parameter is the VendorDefinedReqPayloadStruct.

vTPM will use VendorDefinedPayload to send/receive tpm cmd/rsp. But the VendorDefinedPayload doesn't contains the usertd-id information (the usertd-id is populated by VMM/QEMU and is parsed by transport_encap layer).

**Comment by jyao1** [comment]
I think we need add some context registration mechanism.

**Comment by jyao1** [comment]
check with @mxu9, this is no longer needed for VDM.
