### ISSUE TITLE
[Bug] Use send_secured_message to send vendor_define command the value of is_app_messsage shall be false.

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#395]
Can someone add some comments to `is_app_message` parameter?
 
https://github.com/jyao1/rust-spdm/blob/86bede39d97c3b038019c2909bb6e22da4ddba06/spdmlib/src/responder/vendor_rsp.rs#L40

https://github.com/jyao1/rust-spdm/blob/86bede39d97c3b038019c2909bb6e22da4ddba06/spdmlib/src/requester/vendor_req.rs#L35

**Comment by longlongyang** [comment]
This is a bug, should be false
