### ISSUE TITLE
enum_builder! shall not set Unknown(0) as default

### ISSUE THREAD

**Issue by mxu9** [jyao1/rust-spdm#411]
enum_builder! set Unkown(0) as default. But SpdmSessionState has 0 as SpdmSessionNotStarted.

**Comment by jyao1** [comment]
Would you please be specific? Which code need fix?

**Comment by mxu9** [comment]
In the definition of enum_builder, unknown is set as 0. See https://github.com/jyao1/rust-spdm/blob/master/codec/src/macros.rs#L31

In practice when rust-spdm uses enum_builder to define enum, there always be 0 enum. SpdmSessionState is an example. SpdmSessionNotStarted is 0. See https://github.com/jyao1/rust-spdm/blob/master/spdmlib/src/common/session.rs#L27

This is conflicted with the unknown(0).

My suggestion is to set unknown as :

- if Enum is u8, then unknown is set as 0xff
- if Enum is u16, then unknown is set as 0xffff
- if Enum is u32, then unknown is set as 0xffffffff

**Comment by jyao1** [comment]
I checked https://github.com/rustls/rustls/blob/main/rustls/src/msgs/macros.rs.

Let's remove default.
