### ISSUE TITLE
enum_builder! need to implement from()/try_from()

### ISSUE THREAD

**Issue by mxu9** [jyao1/rust-spdm#412]
Sometimes we need to convert a numeric to an enum. Here is an example:
enum_builder! {
    @U8
    EnumName: TdVtpmOperation;
    EnumVal{
        None => 0x0,
        Communicate => 0x1,
        Create => 0x2,
        Destroy => 0x3,
    }
}

Once we receive an incoming data from VMM, we need to check some field in the data to see what the TdVtpmOperation is. In this case, from()/try_from() can do this conversion.

**Comment by jyao1** [comment]
Would you please be specific? Which code need fix?

**Comment by jyao1** [comment]
check with @mxu9, this is no longer needed.
