### ISSUE TITLE
use case to run test with test key

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-spdm#43]
Current design does not have test key as input parameter. So we only support below 5 cases:
1) Visual Studio Code: debug
2) Visual Studio Code: run
3) command line: cargo test
4) command line: cargo run
5) arbitrary dir (local machine): run .exe

We do NOT support below case:
6) arbitrary dir (copy exe/test key to remote machine): run .exe -- not supported, unless all path are same.
Reason: test key dir is not a parameter.

**Comment by xiaoyuxlu** [comment]
https://doc.rust-lang.org/cargo/reference/environment-variables.html
spmdlib use https://doc.rust-lang.org/cargo/reference/environment-variables.html
CARGO_MANIFEST_DIR
