### ISSUE TITLE
SpdmAlgorithmsResponsePayload::spdm_read lacks input checking

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#448]
For example: 

If response provide a negative ```AlgCount[3:0] = 2```, ```SpdmAlgorithmsResponsePayload::spdm_read( ``` still returns success.

![image](https://github.com/jyao1/rust-spdm/assets/50605570/f1d8d49d-846e-4757-ad44-0cf2e000bf87)

**Comment by jyao1** [comment]
https://github.com/jyao1/rust-spdm/pull/516 added check for ext_alg_count.

Only 0 is allowed. We dont support ext_algo.
