### ISSUE TITLE
Responder/Requester need validate the acceptability of RequestResponseCode based on session status

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#514]
eg: GET_VERSION in session should be prohibited.

Ref: SPDM0274: SPDM request and response messages validity.

**Comment by jyao1** [comment]
Is that already done?

Can you create a case to send GET_VERSION in session ?

**Comment by xiaoyuxlu** [comment]
Indeed, some checks have already done in dispatch_secured_message. 
Furthermore I think we need more checks in dispatch_message.
If requester send a GET_VERSION request when there is an existed/activated session, I think responder should deny the request.

**Comment by jyao1** [comment]
> If requester send a GET_VERSION request when there is an existed/activated session, I think responder should deny the request.

No. It should allow GET_VERSION and stop all sessions.
Please double check if that is the case. If no, then please file an issue.
