### ISSUE TITLE
investigate how to merge the multiple fuzzing report for code coverage.

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-spdm#59]

**Comment by haowqs** [comment]
LLVM_PROFILE_FILE Add parameter %Nm, for example, LLVM_PROFILE_FILE='rspversion%2m.profraw' cargo afl fuzz -i fuzz-target/in -o fuzz-target/out/rspversion target/debug/rspversion, the file that was too large before without parameters cannot be merge.
Link: https://doc.rust-lang.org/beta/unstable-book/compiler-flags/instrument-coverage.html
![image](https://user-images.githubusercontent.com/39472702/127129313-27675364-96ee-40de-b821-76f3ed5cc814.png)
