### ISSUE TITLE
spdmlib_crypto_mbedtls test fail.

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#595]
---- dhe_impl::tests::test_case0_dhe stdout ----
thread 'dhe_impl::tests::test_case0_dhe' panicked at 'range end index 97 out of range for slice of length 96', spdmlib/src/protocol/algo.rs:1088:10

**Comment by jyao1** [comment]
My gut feeling is `const MAX_PRIVATE_KEY_LEN: usize = 512;`

Question: Why it is 512???

**Comment by jyao1** [comment]
Below is suspicious:
```
fn mbedtls_public_key_to_spdm_public_key(origin: SpdmDheExchangeStruct) -> SpdmDheExchangeStruct {
    let mut key = SpdmDheExchangeStruct {
        data_size: origin.data_size - 1,
        data: [0u8; SPDM_MAX_DHE_KEY_SIZE],
    };
    key.data[0..(key.data_size as usize)].copy_from_slice(&origin.as_ref()[1..]); <== 
    key
}

fn spdm_public_key_to_mbedtls_public_key(origin: SpdmDheExchangeStruct) -> SpdmDheExchangeStruct {
    let mut key = SpdmDheExchangeStruct::default();
    key.data[0] = 0x04;
    key.data_size = origin.data_size + 1;
    key.data[1..(key.data_size as usize)].copy_from_slice(origin.as_ref()); <==
    key
}

```

**Comment by xiaoyuxlu** [comment]
> My gut feeling is `const MAX_PRIVATE_KEY_LEN: usize = 512;`
> 
> Question: Why it is 512???
I think this buffer size is enough to store privatekey.

But this might not be a good implementation. The private key should not be exported from mbedtls context. 
I created a new issue for it. https://github.com/jyao1/rust-spdm/issues/595.
