### ISSUE TITLE
The implementation of mbedtls binding doesn't use BytesMut at all. Use the raw u8 slice.

### ISSUE THREAD

**Issue by longlongyang** [jyao1/rust-spdm#605]
> this is for ring only. Do we need this for mbedtls binding?

The implementation of mbedtls binding doesn't use BytesMut at all. Use the raw u8 slice.
How about let's create a new issue to track this?

_Originally posted by @longlongyang in https://github.com/jyao1/rust-spdm/pull/603#discussion_r1198788591_

**Comment by jyao1** [comment]
See issue: https://github.com/jyao1/rust-spdm/issues/585

**Comment by xiaoyuxlu** [comment]
Not a problem in mbedtls binding. It doesn't make any copies for plaintext and key.
