### ISSUE TITLE
check `None` session before unwrap in `send_receive_spdm_finish`

### ISSUE THREAD

**Issue by xiaotia3** [jyao1/rust-spdm#627]
The session may teardown in `handle_spdm_finish_response` internal error handling. 
I think we need handle `None` case of session before `.unwrap()` to avoid panic.

https://github.com/jyao1/rust-spdm/blob/e6d88f7e16538c2d16354e6315ae59708a3c08bc/spdmlib/src/requester/finish_req.rs#L71-L82

**Comment by jyao1** [comment]
get_session_via_id is checked before. Why we need check again?

```
        if self.common.get_session_via_id(session_id).is_none() {
            return Err(SPDM_STATUS_INVALID_PARAMETER);
        }
```

**Comment by xiaotia3** [comment]
Because in `handle_spdm_finish_response()`, if there is an error SpdmRequestResponseCode, the session possibly teardown and the session id would be set with invalid:

https://github.com/jyao1/rust-spdm/blob/e6d88f7e16538c2d16354e6315ae59708a3c08bc/spdmlib/src/requester/handle_error_response_req.rs#L74-L83

and although we have checked none session before, `get_session_via_id` will still possible to be none after `handle_spdm_finish_response()`

**Comment by jyao1** [comment]
Got it. That is a bug.
