### ISSUE TITLE
need write error before return in `write_spdm_algorithm`

### ISSUE THREAD

**Issue by xiaotia3** [jyao1/rust-spdm#645]
If it fails to get root hash and returns directly, then `send_message` will panic because it is trying to get opcode from an empty send buffer.

https://github.com/jyao1/rust-spdm/blob/3dd062f061fe9e5c7f6dc97cf0b1462c71a4e17d/spdmlib/src/responder/algorithm_rsp.rs#L145-L154

https://github.com/jyao1/rust-spdm/blob/3dd062f061fe9e5c7f6dc97cf0b1462c71a4e17d/spdmlib/src/responder/context.rs#L48

**Comment by jyao1** [comment]
@xiaotia3 , do you want to propose a patch?

**Comment by xiaotia3** [comment]
> 

Absolutely! I think it is easy to fix
