### ISSUE TITLE
Should remove duplicate test code. 

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-spdm#678]
spdmlib/src/testlib.rs
spdmlib/tests/common/testlib.rs

Follow the rust convention, integration tests go in the `tests` directory.

**Comment by xiaoyuxlu** [comment]
Thanks @xiaotia3 for pointing this issue out.

**Comment by jyao1** [comment]
ref: https://github.com/jyao1/rust-spdm/issues/598
