### ISSUE TITLE
need propagate the error back to handle_spdm_xxx function

### ISSUE THREAD

**Issue by longlongyang** [jyao1/rust-spdm#692]
Currently, in responder code, the write_xxx function doesn't propagate the error back to handle_spdm_xxx function. 
For example:

https://github.com/jyao1/rust-spdm/blob/746d38ea54875121a0ef036fd0c7bb722fc7ee41/spdmlib/src/responder/algorithm_rsp.rs#L13-L18

if some error happens inside `self.write_spdm_algorithm(bytes, &mut writer); ` , line 17 will still be called, a unexpected buffer will be sent to requester, and if the send is good, then handle_spdm_algorithm will return Ok result.

**Comment by jyao1** [comment]
NOTE: If write_spdm_algorithm() gets error, it may construct error_message. As such, send_message() is right behavior.

If only the write_spdm_xxx() does not want to return error_message but drop the request, then error should be returned.

**Comment by jyao1** [comment]
@mxu9 could you please propose the use case?
We need consider 3 kinds of error:
* error message
* error status
* message drop

**Comment by jyao1** [comment]
See https://github.com/intel/rust-spdm/issues/44
