### ISSUE TITLE
Unit tests for responder miss the check of the result and the correctness of response message

### ISSUE THREAD

**Issue by gaojiaqi7** [jyao1/rust-spdm#706]
For example:

https://github.com/jyao1/rust-spdm/blob/987673e7d1d2137d7d184f24f2060c36118e82d4/spdmlib/src/responder/digest_rsp.rs#L190
https://github.com/jyao1/rust-spdm/blob/987673e7d1d2137d7d184f24f2060c36118e82d4/spdmlib/src/responder/certificate_rsp.rs#L206
https://github.com/jyao1/rust-spdm/blob/987673e7d1d2137d7d184f24f2060c36118e82d4/spdmlib/src/responder/challenge_rsp.rs#L346

I think unit tests should check:
 - Is the result of tested method `Ok` or not.
 - Is the response message sent from tested method expected or not.

**Comment by jyao1** [comment]
See https://github.com/intel/rust-spdm/issues/36
