### ISSUE TITLE
when target_os is none, get certificate failed at verify_cert_chain_with_eku due to incorrect timestamp.

### ISSUE THREAD

**Issue by longlongyang** [jyao1/rust-spdm#709]
when target_os is none, get certificate will fail at verify_cert_chain_with_eku due to incorrect timestamp.
the error shows as:
```
2023-06-16 08:15:02,492 INFO [spdmlib::requester::get_certificate_req] 1. get runtime_peer_cert_chain_data!

2023-06-16 08:15:02,492 ERROR [spdmlib::crypto::spdm_ring::cert_operation_impl] Cert verification Fail

2023-06-16 08:15:02,493 ERROR [spdmlib::requester::get_certificate_req] cert_chain verification - fail! - TBD later

thread 'main' panicked at 'send_receive_spdm_certificate failed!', test/spdm-requester-emu/src/main.rs:210:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

the timestamp is got from uefi_time::get_rtc_time(), which is a constant [1632816005](https://github.com/jyao1/rust-uefi-time/blob/7c97e42e6948abd974fb069154f29788bd85b9d2/src/lib.rs#L9-L22). 
https://github.com/jyao1/rust-spdm/blob/b25745ae15100fe899776a00fe4fd88c3ac8ce81/spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs#L92-L105

https://github.com/jyao1/rust-spdm/blob/b25745ae15100fe899776a00fe4fd88c3ac8ce81/spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs#L112-L129

option 1:
remove this check call `verify_cert_chain_with_eku`.
option 2:
correct the uefi_time::get_rtc_time implementation.

**Comment by longlongyang** [comment]
step to reproduce:
replace the timestamp with hardcode value 1632816005
https://github.com/jyao1/rust-spdm/blob/b25745ae15100fe899776a00fe4fd88c3ac8ce81/spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs#L104
cargo run -p spdm-responder-emu --no-default-features --features=spdm-ring,hashed-transcript-data
cargo run -p spdm-requester-emu --no-default-features --features=spdm-ring,hashed-transcript-data

OR

./spdm_responder_emu --trans PCI_DOE --asym ECDSA_P384
cargo run -p spdm-requester-emu --no-default-features --features=spdm-ring,hashed-transcript-data

**Comment by jyao1** [comment]
@longlongyang why did it pass before?

**Comment by longlongyang** [comment]
> @longlongyang why did it pass before?

Before:
the verify_spdm_certificate_chain function will check provision_info first, If no certificates were provisioned, then will return as if it is not called ever.
https://github.com/jyao1/rust-spdm/blob/75847e0a6b96ffd206da3c02d67841d3fc7afb17/spdmlib/src/requester/get_certificate_req.rs#L207-L212

Now:
the verify_spdm_certificate_chain function will perform verification all the time.
https://github.com/jyao1/rust-spdm/blob/b25745ae15100fe899776a00fe4fd88c3ac8ce81/spdmlib/src/requester/get_certificate_req.rs#L228-L235

So this issue is not exposed before since it is skipped. and now it shows up.

**Comment by jyao1** [comment]
it could be fixed by https://github.com/jyao1/rust-spdm/pull/711
